# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PokemonList2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokemonList2
pod "Alamofire"
pod "SDWebImage"
  target 'PokemonList2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PokemonList2UITests' do
    # Pods for testing
  end

end
